apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: secret-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-db
spec:      
  replicas: 1
  selector:
    matchLabels:
      app: secret-db
  template:
    metadata:
      labels:
        app: secret-db
    spec:
      nodeSelector:
        inferx_storage: data
      containers:
        - name: postgres
          image: inferx/inferx_postgres:${VERSION}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: secret
            - name: POSTGRES_PASSWORD
              value: "123456"
            - name: POSTGRES_DB
              value: secretdb
            - name: PGDATA
              value: /data/postgres
            - name: INIT_SQL
              value: secret.sql 
          volumeMounts:
            - name: db-data
              mountPath: /data/postgres
      volumes:
        - name: db-data
          hostPath:
            path: /opt/inferx/data/postgres_secret
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: secret-db
spec:
  selector:
    app: secret-db
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30541
  type: NodePort
